general_cfg:
  algo_name: PPO
  device: cuda
  env_name: CartPole-v1
  eval_eps: 20
  eval_per_episode: 5
  load_checkpoint: true
  load_path: Train_CartPole-v1_PPO_20221114-132315
  max_steps: 200
  mode: test
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 100
algo_cfg:
  actor_hidden_dim: 256
  actor_lr: 0.0003
  batch_size: 5
  continuous: false
  critic_hidden_dim: 256
  critic_lr: 0.0003
  gae_lambda: 0.95
  gamma: 0.99
  n_epochs: 4
  policy_clip: 0.2
  update_fre: 20
