general_cfg:
  algo_name: A2C
  device: cuda
  env_name: CartPole-v1
  mode: test
  load_checkpoint: true
  load_path: Train_CartPole-v1_A2C_20221031-232138
  max_steps: 200
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 20
  train_eps: 1000
algo_cfg:
  continuous: false
  batch_size: 64
  buffer_size: 100000
  gamma: 0.99
  actor_lr: 0.0003
  critic_lr: 0.001
  target_update: 4
