general_cfg:
  algo_name: Sarsa
  device: cpu
  env_name: CliffWalking-v0
  mode: test
  load_checkpoint: true
  load_path: Train_CliffWalking-v0_Sarsa_20221030-021146
  max_steps: 200
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 20
  train_eps: 400
algo_cfg:
  epsilon_decay: 300
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.95
  lr: 0.1
